const PREGUNTAS = {
  ciudadano: [
    {
      id: 'nombre',
      label: 'Nombre completo',
      type: 'text',
      required: false,
      placeholder: 'Opcional',
    },
    {
      id: 'edad',
      label: 'Rango de edad',
      type: 'select',
      required: true,
      options: ['18–30', '31–45', '46–60', 'Más de 60'],
    },
    {
      id: 'residencia',
      label: '¿Hace cuánto tiempo vive en el barrio?',
      type: 'select',
      required: true,
      options: ['Menos de 1 año', '1 a 5 años', '5 a 10 años', 'Más de 10 años'],
    },
    {
      id: 'calidad_vida',
      label: '¿Cómo evaluaría la calidad de vida en el barrio?',
      type: 'scale',
      required: true,
      labels: ['Muy mala', 'Mala', 'Regular', 'Buena', 'Muy buena'],
    },
    {
      id: 'problemas',
      label: '¿Cuáles son los principales problemas que nota en el barrio?',
      type: 'checkbox',
      required: false,
      options: ['Seguridad', 'Limpieza', 'Iluminación', 'Estado de calles', 'Espacios verdes', 'Transporte público', 'Otro'],
    },
    {
      id: 'mejoras',
      label: '¿Qué mejoras le gustaría ver en el barrio?',
      type: 'textarea',
      required: false,
      placeholder: 'Describa las mejoras que considera necesarias…',
    },
    {
      id: 'comentarios',
      label: 'Comentarios adicionales',
      type: 'textarea',
      required: false,
      placeholder: 'Cualquier otra información relevante…',
    },
  ],

  problematica: [
    {
      id: 'categoria',
      label: 'Categoría del problema',
      type: 'select',
      required: true,
      options: [
        'Bache / Grieta en calzada',
        'Suciedad / Basura acumulada',
        'Luminaria apagada o rota',
        'Vereda en mal estado',
        'Problema cloacal',
        'Árbol caído o peligroso',
        'Poda necesaria',
        'Otro',
      ],
    },
    {
      id: 'direccion',
      label: 'Referencia de ubicación',
      type: 'text',
      required: false,
      placeholder: 'Ej: Av. San Martín 1234, esquina Rivadavia',
    },
    {
      id: 'descripcion',
      label: 'Descripción del problema',
      type: 'textarea',
      required: true,
      placeholder: 'Describa detalladamente el problema observado…',
    },
    {
      id: 'urgencia',
      label: '¿Cuál es el nivel de urgencia?',
      type: 'radio',
      required: true,
      options: [
        { value: 'bajo',  label: 'Bajo — no requiere atención inmediata' },
        { value: 'medio', label: 'Medio — requiere atención en los próximos días' },
        { value: 'alto',  label: 'Alto — riesgo para personas o el tránsito' },
      ],
    },
    {
      id: 'afecta_transito',
      label: '¿El problema afecta el tránsito vehicular o peatonal?',
      type: 'radio',
      required: true,
      options: [
        { value: 'si', label: 'Sí' },
        { value: 'no', label: 'No' },
      ],
    },
    {
      id: 'observaciones',
      label: 'Observaciones adicionales',
      type: 'textarea',
      required: false,
      placeholder: 'Información adicional relevante…',
    },
  ],
};
